service: Dotabook-public
package:
  excludeDevDependencies: true

provider:
  name: aws
  stage: PROD
  memorySize: 3008
  timeout: 30
  runtime: nodejs8.10
  region: ap-southeast-2
  profile: perso
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource: '*'
functions:
  getOpenidUrl:
    handler: authentication/openid.getUrl
  getProfile:
    handler: authentication/profile.handler
  getMatchHistory:
    handler: getMatchHistory/getMatchHistory.handler
  updateNote:
    handler: updateNote/updateNote.handler
  getMatchDetails:
    handler: getMatchDetails/getMatchDetails.handler
  searchUser:
    handler: searchUser/searchUser.handler
