service: Dotabook-public
package:
  excludeDevDependencies: true

provider:
  name: aws
  stage: PROD
  memorySize: 3008
  timeout: 30
  runtime: nodejs8.10
  region: ap-southeast-2
  profile: perso
  iamRoleStatements:
    - Effect: Allow
      Action:
        - 'dynamodb:*'
      Resource: '*'

functions:
  getOpenidUrl:
    handler: authentication/openid.getUrl
    events:
      - http:
          path: login
          method: get
          cors:
            origin: '*'
  getProfile:
    handler: authentication/profile.handler
    events:
      - http:
          path: profile
          method: get
          request:
            parameters:
              paths:
                profileId: true
          cors:
            origin: '*'
  getMatchHistory:
    handler: getMatchHistory/getMatchHistory.handler
    events:
      - http:
          path: match/history
          method: get
          request:
            parameters:
              paths:
                profileId: true
          cors:
            origin: '*'
  getMatchDetails:
    handler: getMatchDetails/getMatchDetails.handler
    events:
      - http:
          path: match/
          method: get
          request:
            parameters:
              paths:
                matchId: true
          cors:
            origin: '*'
